apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client-deployment # id of the deployment
spec: #its specification
  replicas: 3
  selector:
    matchLabels:
      component: web # what is the component of our app?
  template: 
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: eugocker/multi-client
          ports:
            - containerPort: 3000