# to describe our cert manager where to get the certificate
apiVersion: cert-manager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # a link to letsencrypt api
    email: 'bratikha@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {
      
    }